spring.application.name=bank-service

# ===========
# Database
# ===========
spring.datasource.url=jdbc:mysql://localhost:3306/bank_service?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# Docker Compose
# ===============================
spring.docker.compose.enabled=false

#================
# JWT (Base64)
#================
jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# ==========================
# REDIS CONFIGURATION
# ==========================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

# TTL chung cho cache (phút)
app.cache.ttl-minutes=10